---

- name: Generate Client config file
  template:
    src: "etc/openvpn/client.conf.j2"
    dest: "{{ openvpn_dir }}/{{ openvpn_file }}"
    owner: root
    group: root
    mode: 0400
  notify:
    - Restart OpenVpn
  become: yes