- hosts: control
  tasks:
   - name: Run the equivalent of "apt-get update" as a separate step
     become: yes
     apt:
       update_cache: yes
       cache_valid_time: 3600

   - name: Update all packages to the latest version
     become: yes
     apt:
       upgrade: dist

   - name: Install soft
     become: yes
     apt:
       name:
         - mc
         - wget
         - nano
         - curl
         - mtr
         - snmp
         - speedtest-cli
         - dnsutils
         - jq
         - zsh
         - git
         - sudo
         - tree
         - tmux
         - lsof
         - htop
         - iotop
         - iftop
         - iperf
         - ngrep
         - tcpdump
         - sipgrep
         - sngrep

   - name: "Copy .zshrc"
     copy:
      src: .zshrc
      dest: "/home/{{ user_name }}/.zshrc" 
     notify:
      - fix permissions
