---
   - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
     become: yes
     apt:
       update_cache: yes
       cache_valid_time: 3600

   - name: Update all packages to the latest version
     become: yes
     apt:
       upgrade: dist

   - name: Install soft
     become: yes
     apt:
       name:
        - mc
        - wget
        - nano
        - curl
        - mtr
        - snmp
        - speedtest-cli
        - dnsutils
        - jq
        - zsh
        - git
        - sudo
        - tree
        - tmux
        - lsof
        - htop
        - iotop
        - iftop
        - iperf
        - ngrep
        - tcpdump
        - sipgrep
        - sngrep
        - whois
        - neofetch

   - name: Copy .zshrc to {{ user_name }}
     copy:
       src: zshrc
       dest: "~/.zshrc"
     notify: 
       - fix permissions
    
   - name: Set shell zsh
     become: yes
     user:
       name: "{{ user_name }}"
       shell: /bin/zsh
     - group: name=sudo state=present

   - name: Add Vit user and add it to sudo
     user: name=vit
          state=present
          createhome=yes
          shell=/bin/zsh
     become: yes    

   - name: Set up authorized keys for the deployer user
     authorized_key: user=vit key="{{item}}"
     with_file:
      - id_rsa.pub

   - name: Copy .zshrc to vit
     copy:
       src: zshrc
       dest: "/home/vit/.zshrc"
     notify: 
       - fix permissions vit