---
- name: Install qBittorrent
  apt:
    name: qbittorrent-nox
  become: yes

- name: Copy systemd service file to server
  copy:
    src: qbittorrent-nox.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start qbittorrent
