---
- name: Create a new user login
     user:
      name: {{ new_user_name }}
      password: {{ new_user_pass }}
      #groups: docker, sudo   # Empty by default.
      state: present
      shell: /bin/bash       # Defaults to /bin/bash
      system: no             # Defaults to no
      createhome: yes        # Defaults to yes
      home: /home/{{ new_user_name }}  # Defaults to /home/<username>
