- name: fix permissions
  file:
    path: '/home/{{ user_name }}/'
    owner: '{{ user_name }}'
    group: '{{ user_name }}'
    state: directory
    recurse: yes

- name: fix permissions vit
  file:
    path: '/home/vit/'
    owner: 'vit'
    group: 'vit'
    state: directory
    recurse: yes
